---
language: node_js
node_js:
  - "10"

dist: trusty

addons:
  chrome: stable
  firefox: latest

cache:
  yarn: true
  directories:
    - $HOME/.cache

jobs:
  fail_fast: true
  include:
    - stage: 'Tests'
      env: EMBER_TRY_SCENARIO=ember-1.13
    - env: EMBER_TRY_SCENARIO=ember-lts-2.4
    - env: EMBER_TRY_SCENARIO=ember-lts-2.8
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

    - stage: 'Deploy'
      if: tag IS present
      script: skip     # usually you do not want to rerun any tests
      deploy:
        provider: npm
        email: info@simplabs.com
        api_key:
          secure: PA0X+4BPH2ACTKsOJQ5/018XKB6OZ3jUR5le/8ILCIfsCJUTSe1qKjv2qu10fhRDsUd1/HXSiqDWk4xnbencrkK5QhYkpR+6r2ryu01yGXqy3sKHxSZRdy7to0XHMUY55l5avvZPCUOohQljdEqb2zksSP26AfIDq3hXmqjvLaKyN/rV7KzG5X+a77WO0BMXefogBGA5HV8o7irKNMaU04z5XoKvzqJoVH9Mjc58YPLtC/8BYIO0dpkBiAxdEkz1pioha1SRgtQEhvfcK+8xoo+iCMglx6FvbuHI4GRHLgBGYfBDzuebqCgKgY1oiMLVoZpzhFs/qLpUGsZMZLkGQD0OPDidrnDPHaGERJIu/GC5lPuyRAtIYSfTJCT93Y30ZyHSJwgDEu4x4wO3Xy+3uXqo1y1kx8DE2moDFhrxeDlTZTQdt1+HDmwTFwLn9iZHngJLU5Yzf+5dGV3eREig0pjyBSBKK1a2jZO/YOxUYeYUkDxRjon6DyGMwi+DP59HHsr23Shntt70lUrmyBJTfBo1OQDB0OzeyLN7n+Q/ybpFqO58uVRE2w+eGepm9pDWeb1uWX+tSvBc7PTBdE+8aAQkUDfCEIZ916Oq4ijpkW/Bt83LncxmLb9Sd8/UKyG0ozkZgvgTqbJaRQef9IewYv9tfsneDqYsSdDHSwUfQDw=
        on:
          repo: simplabs/ember-cookies

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never
